configure: Refactor the configure script again
Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,15 +9,10 @@
 
 set -e;
 
-cc=${CC:-gcc};
-cxx=${CXX:-g++};
-ld=${LD:-$cc};
+cc=${CC:-cc};
+cxx=${CXX:-c++};
+ld=${LD:-$cxx};
 build_dir=${O:-$(dirname $(realpath $0))};
-
-USER_CFLAGS="${CFLAGS}";
-USER_CXXFLAGS="${CXXFLAGS}";
-USER_LDFLAGS="${LDFLAGS}";
-USER_LIB_LDFLAGS="${LIB_LDFLAGS}";
 
 for opt do
 	optarg=$(expr "x$opt" : 'x[^=]*=\(.*\)' || true);
@@ -31,26 +26,17 @@ for opt do
 	--prefix=*)
 		prefix="$optarg";
 	;;
-	--includedir=*)
-		includedir="$optarg";
-	;;
-	--libdir=*)
-		libdir="$optarg";
-	;;
-	--libdevdir=*)
-		libdevdir="$optarg";
-	;;
 	--mandir=*)
 		mandir="$optarg";
-	;;
-	--datadir=*)
-		datadir="$optarg";
 	;;
 	--cc=??*)
 		cc="$optarg";
 	;;
 	--cxx=*)
 		cxx="$optarg";
+	;;
+	--lto)
+		use_lto="yes";
 	;;
 	--gui)
 		use_gui="yes";
@@ -65,30 +51,6 @@ for opt do
 	;;
 	esac;
 done
-
-if test -z "$prefix"; then
-	prefix=/usr;
-fi
-
-if test -z "$includedir"; then
-	includedir="$prefix/include";
-fi
-
-if test -z "$libdir"; then
-	libdir="$prefix/lib";
-fi
-
-if test -z "$libdevdir"; then
-	libdevdir="$prefix/lib";
-fi
-
-if test -z "$mandir"; then
-	mandir="$prefix/man";
-fi
-
-if test -z "$datadir"; then
-	datadir="$prefix/share";
-fi
 
 if test "$show_help" = "yes"; then
 cat <<EOF
@@ -106,14 +68,23 @@ Options: [defaults in brackets after descriptions]
   --datadir=PATH           Install shared data in PATH [$datadir]
   --cc=CMD                 Use CMD as the C compiler
   --cxx=CMD                Use CMD as the C++ compiler
+  --lto                    Compile with link-time optimization
   --gui                    Add the GUI support
   --debug                  Build with debug enabled
 EOF
 exit 0;
 fi
 
-mkdir -pv "${build_dir}";
-build_dir="$(realpath "${build_dir}")";
+if test -z "$prefix"; then
+	prefix=/usr;
+fi
+
+if test -z "$mandir"; then
+	mandir="$prefix/man";
+fi
+
+mkdir -p "${build_dir}";
+build_dir="$(realpath -e "${build_dir}")";
 
 tmp_dir="${build_dir}/.tmp";
 tmp_o="${tmp_dir}/tmp.o";
@@ -121,12 +92,12 @@ tmp_c="${tmp_dir}/tmp.c";
 tmp_cpp="${tmp_dir}/tmp.cpp";
 tmp_exe="${tmp_dir}/tmp.exe";
 
-mkdir -pv "${tmp_dir}";
+mkdir -p "${tmp_dir}";
 rm -f "${build_dir}/config.log";
 
 config_make="${build_dir}/config.make";
-config_h="${build_dir}/config.h";
 config_log="${build_dir}/config.log";
+config_h="${build_dir}/config.h";
 
 # NB: do not call "exit" in the trap handler; this is buggy with some shells;
 # see <1285349658-3122-1-git-send-email-loic.minier@linaro.org>
@@ -144,49 +115,19 @@ fatal()
 # Print result for each configuration test
 print_config()
 {
-	printf "  %-55s%s\n" "$1" "$2";
+	printf "  %s %s\n" "$1" "$2";
 }
 
-# Default flags.
-CFLAGS="-O2 -D_GNU_SOURCE -include ${build_dir}/config.h";
-CXXFLAGS="-O2 -D_GNU_SOURCE -include ${build_dir}/config.h";
-LDFLAGS="-O2";
-LIB_LDFLAGS="-lpthread";
-
-# Print configure header at the top of $config_h.
-printf "/*\n" > $config_h;
-printf " * Automatically generated by configure - do not modify!\n" >> $config_h;
-printf " *\n" >> $config_h;
-printf " * Configured with:" >> $config_h;
-printf " * '%s'" "$0" "$@" >> $config_h;
-printf "\n" >> $config_h;
-printf " */\n" >> $config_h;
-
-printf "# Automatically generated by configure - do not modify!\n" > $config_make;
-printf "# Configured with:" >> $config_make;
-printf " '%s'" "$0" "$@" >> $config_make;
-printf "\n" >> $config_make;
-
-add_config_make()
+# Append a string to $config_h.
+p_conf_h()
 {
-	printf "%s\n" "$1=$2" >> $config_make;
+	printf "$@" >> "${config_h}";
 }
 
-add_config_h()
+# Append a string to $config_make.
+p_conf_make()
 {
-	printf "%s\n" "#define $1" >> $config_h;
-}
-
-add_config()
-{
-	add_config_make $1 "y";
-	add_config_h $1;
-	print_config "Adding $1=y";
-}
-
-add_make_var()
-{
-	printf "%s\n" "$1=$2" >> $config_make;
+	printf "$@" >> "${config_make}";
 }
 
 do_cc()
@@ -207,103 +148,130 @@ do_cxx()
 
 compile_cc()
 {
-	local_cflags="$1";
-	local_ldflags="$2 $LIBS";
+	local_ccflags="$1";
+	local_ldflags="$2";
 	printf "\n\nCompiling test case %s:\n" "$3" >> $config_log;
-	do_cc $CFLAGS $local_cflags -o "${tmp_exe}" "${tmp_c}" \
-		${LDFLAGS} ${local_ldflags};
+	do_cc -o "${tmp_o}" -c "${tmp_c}" ${local_ccflags} ${local_ldflags};
 }
 
 compile_cxx()
 {
 	local_cxxflags="$1";
-	local_ldflags="$2 $LIBS";
-	printf "\n\nCompiling test case %s:" "$3" >> $config_log;
-	do_cxx $CXXFLAGS $local_cxxflags -o "${tmp_exe}" "${tmp_cpp}" \
-		${LDFLAGS} ${local_ldflags};
+	local_ldflags="$2";
+	printf "\n\nCompiling test case %s:\n" "$3" >> $config_log;
+	do_cxx -o "${tmp_o}" -c "${tmp_cpp}" ${local_cxxflags} ${local_ldflags};
 }
 
-__has_cflags()
+# Same as compile_cxx, but also link the object file (without -c).
+compile_cxx_and_link()
 {
-	cat > $tmp_c << EOF
-int main(void)
-{
-	return 0;
+	local_cxxflags="$1";
+	local_ldflags="$2";
+	printf "\n\nCompiling test case %s:\n" "$3" >> $config_log;
+	do_cxx -o "${tmp_o}" "${tmp_cpp}" ${local_cxxflags} ${local_ldflags};
 }
-EOF
+
+has_cflag()
+{
+	printf "%s\n" "int main(void) { return 0; }" > $tmp_c;
 	compile_cc "-Werror $1" "" "$1" || return $?;
 	return 0;
 }
 
-__has_cxxflags()
+has_cxxflag()
 {
-	cat > $tmp_cpp << EOF
-int main(void)
-{
-	return 0;
-}
-EOF
+	printf "%s\n" "int main(void) { return 0; }" > $tmp_cpp;
 	compile_cxx "-Werror $1" "" "$1" || return $?;
 	return 0;
 }
 
-__has_c_and_cxxflags()
+has_ldflag()
 {
-	__has_cflags $1 || return $?;
-	__has_cxxflags $1 || return $?;
+	printf "%s\n" "int main(void) { return 0; }" > $tmp_c;
+	printf "\n\nCompiling test case %s:\n" "$1" >> $config_log;
+	compile_cxx_and_link "" "$1" "$1" || return $?;
 	return 0;
 }
 
-add_c_flag()
+add_cflag()
 {
-	local_append_flag=$1;
-	if test ! -z "$2"; then
-		local_append_flag="$2";
-	fi;
-
-	if __has_cflags $1; then
+	if has_cflag $1; then
 		ret=0;
-		support="yes";
+		support="y";
 		CFLAGS="$1 ${CFLAGS}";
 	else
 		ret=1;
-		support="no";
+		support="n";
 	fi;
 
-	print_config "Does CC  support ${1}?" "${support}";
+	print_config "CC  has ${1}:" "${support}";
 	return $ret;
 }
 
 add_cxx_flag()
 {
-	local_append_flag=$1;
-	if test ! -z "$2"; then
-		local_append_flag="$2";
-	fi;
-
-	if __has_cxxflags $1; then
-		support="yes";
+	if has_cxxflag $1; then
+		ret=0;
+		support="y";
 		CXXFLAGS="$1 ${CXXFLAGS}";
 	else
-		support="no";
+		ret=1;
+		support="n";
 	fi;
-	ret=$?;
 
-	print_config "Does CXX support ${1}?" "${support}";
+	print_config "CXX has ${1}:" "${support}";
+	return $ret;
+}
+
+add_ldflag()
+{
+	if has_ldflag $1; then
+		ret=0;
+		support="y";
+		LDFLAGS="$1 ${LDFLAGS}";
+	else
+		ret=1;
+		support="n";
+	fi;
+
+	print_config "LD  has ${1}:" "${support}";
 	return $ret;
 }
 
 add_c_and_cxx_flag()
 {
-	add_c_flag "$@";
-	add_cxx_flag "$@";
+	add_cflag $1;
+	add_cxx_flag $1;
 }
 
-printf "\n%s:\n" "Compilers";
-print_config "CC" "${cc}";
-print_config "CXX" "${cxx}";
+# Default flags.
+CXXFLAGS="-O2 -D_GNU_SOURCE -include ${build_dir}/config.h";
+CFLAGS="-O2 -D_GNU_SOURCE -include ${build_dir}/config.h";
+LDFLAGS="-O2";
+LIB_LDFLAGS="-lpthread";
 
-# Don't exit if add_* functions return non-zero.
+rm -f "${config_h}" "${config_make}";
+
+# Print configure header at the top of $config_h.
+p_conf_h "/*\n";
+p_conf_h " * Automatically generated by configure\n";
+p_conf_h " *\n";
+p_conf_h " * Configured with:";
+p_conf_h " '%s'" "$0" "$@";
+p_conf_h "\n";
+p_conf_h " *\n";
+p_conf_h " */\n";
+
+# Print configure header at the top of $config_make.
+p_conf_make "#\n";
+p_conf_make "# Automatically generated by configure\n";
+p_conf_make "#\n";
+p_conf_make "# Configured with:";
+p_conf_make " '%s'" "$0" "$@";
+p_conf_make "\n";
+p_conf_make "#\n";
+
+# Don't exit if add_c_and_cxx_flag calls return non-zero.
 set +e;
 
 printf "\n%s:\n" "-W flags";
@@ -329,46 +297,23 @@ add_c_and_cxx_flag "-fdata-sections";
 add_c_and_cxx_flag "-ffunction-sections";
 add_c_and_cxx_flag "-fno-strict-aliasing";
 add_c_and_cxx_flag "-fvisibility=hidden";
-add_c_and_cxx_flag "-flto" && LDFLAGS="-flto ${LDFLAGS}";
-add_c_and_cxx_flag "-fpie -fPIE" && LDFLAGS="-fpie -fPIE ${LDFLAGS}";
+
+# Append -flto if $use_lto is set.
+if [ -n "${use_lto}" ]; then
+	add_c_and_cxx_flag "-flto" && c_and_cxx_support_lto="y" || c_and_cxx_support_lto="n";
+fi;
 
 printf "\n%s:\n" "Misc flags";
-LDFLAGS="-rdynamic ${LDFLAGS}";
 add_c_and_cxx_flag "-ggdb3" && LDFLAGS="-ggdb3 ${LDFLAGS}";
+add_ldflag "-rdynamic";
+
+if [ -n "${use_lto}" ]; then
+	add_ldflag "-flto";
+fi;
 
 # Bring it back!
 set -e;
-
-printf "\n%s:\n" "CONFIG";
-add_config "CONFIG_POLL";
-add_config "CONFIG_EPOLL";
-add_config "CONFIG_IO_URING";
-add_config "CONFIG_TEAVPN_SERVER";
-add_config "CONFIG_TEAVPN_CLIENT";
-add_config "CONFIG_LINUX";
-
-if test "${use_gui}" = "yes"; then
-	add_config "CONFIG_GUI";
-	gtk3_cflags=`pkg-config --cflags gtk+-3.0`;
-	gtk3_lib_ldflags=`pkg-config --libs gtk+-3.0`;
-	CFLAGS="${CFLAGS} ${gtk3_cflags}";
-	CXXFLAGS="${CXXFLAGS} ${gtk3_cflags}";
-	LIB_LDFLAGS="${LD_FLAGS} ${gtk3_lib_ldflags}";
-fi;
-
-if test "${use_debug}" = "yes"; then
-	add_config "CONFIG_DEBUG";
-else
-	CFLAGS="${CFLAGS} -DNDEBUG";
-	CXXFLAGS="${CXXFLAGS} -DNDEBUG";
-fi;
-
-add_make_var "CC" "${cc}";
-add_make_var "CXX" "${cxx}";
-add_make_var "CFLAGS" "$(echo "${CFLAGS} ${USER_CFLAGS}" | awk '{$1=$1};1')";
-add_make_var "CXXFLAGS" "$(echo "${CXXFLAGS} ${USER_CXXFLAGS}" | awk '{$1=$1};1')";
-add_make_var "LDFLAGS" "$(echo "${LDFLAGS} ${USER_LIB_LDFLAGS}" | awk '{$1=$1};1')";
-add_make_var "LIB_LDFLAGS" "$(echo "${LIB_LDFLAGS} ${USER_LIB_LDFLAGS}" | awk '{$1=$1};1')";
-printf "override O=%s\n" "${build_dir}" >> $config_make;
-ln -s "${config_make}" >> /dev/null 2>&1 || true;
-printf "\n";
+p_conf_make "CFLAGS = %s\n" "${CFLAGS}";
+p_conf_make "CXXFLAGS = %s\n" "${CXXFLAGS}";
+p_conf_make "LDFLAGS = %s\n" "${LDFLAGS}";
+p_conf_make "LIB_LDFLAGS = %s\n" "${LIB_LDFLAGS}";
